"""empty message

Revision ID: bf5c91cad788
Revises: 31fd75cd7785
Create Date: 2023-04-04 13:06:27.920131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5c91cad788'
down_revision = '31fd75cd7785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('origin_planet', sa.String(length=50), nullable=False),
    sa.Column('hair_color', sa.String(length=30), nullable=True),
    sa.Column('eye_color', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('terrain', sa.Integer(), nullable=False),
    sa.Column('liveable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('single_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('eye_color', sa.String(length=20), nullable=True),
    sa.Column('films', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('hair_color', sa.String(length=30), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('homeworld', sa.String(length=50), nullable=False),
    sa.Column('skin_color', sa.String(length=30), nullable=False),
    sa.Column('species', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('single_people')
    op.drop_table('planet')
    op.drop_table('people')
    # ### end Alembic commands ###
